// src/shell/rules-gen.mjs — the security-rules generator (the RBAC module's assembler interface).
// Deterministically emits a firestore.rules file from each dataModel's owner/access + the auth
// roles/capabilities, so ACCESS is a property of the Spec, not hand-maintained. Pure: same input
// ⇒ identical text. See docs/MODULE_RBAC.md §5, docs/ASSEMBLER.md §8.
//
// v0 conventions: the ownership field is `uid`; "admin" roles are those granted '*' or
// 'manage-content' in auth.capabilities, else those with rank >= 80, else [owner, admin].

const str = v => (typeof v === 'string' ? v : '');

function adminRoles(auth) {
  const roles = (auth && Array.isArray(auth.roles)) ? auth.roles : [];
  const caps = (auth && auth.capabilities) || {};
  const byCap = roles
    .map(r => r.id)
    .filter(id => Array.isArray(caps[id]) && (caps[id].includes('*') || caps[id].includes('manage-content')));
  if (byCap.length) return byCap;
  const byRank = roles.filter(r => typeof r.rank === 'number' && r.rank >= 80).map(r => r.id);
  if (byRank.length) return byRank;
  return ['owner', 'admin'];
}

const list = ids => '[' + ids.map(id => `'${id}'`).join(', ') + ']';

function modelBlock(model, admins) {
  const coll = str(model.id) || 'items';
  const access = str(model.access) || 'admin-read';
  let body;
  if (access === 'owner-read') {
    body =
`      allow read, update, delete: if signedIn() && request.auth.uid == resource.data.uid;
      allow create: if signedIn() && request.auth.uid == request.resource.data.uid;`;
  } else if (access === 'public') {
    body =
`      allow read: if signedIn();
      allow write: if hasRole(${list(admins)});`;
  } else { // admin-read (default)
    body =
`      allow read, write: if hasRole(${list(admins)});`;
  }
  return `    // dataModel "${coll}" — access: ${access}\n    match /${coll}/{docId} {\n${body}\n    }`;
}

export function genRules(dataModels, auth) {
  const admins = adminRoles(auth);
  const models = (Array.isArray(dataModels) ? dataModels : []).map(m => modelBlock(m, admins)).join('\n\n');
  return `rules_version = '2';
// GENERATED by the assembler from the App Spec (dataModels + auth). Do not hand-edit —
// change the Spec and re-run gen-rules. See docs/MODULE_RBAC.md §5.
service cloud.firestore {
  match /databases/{database}/documents {

    function signedIn() { return request.auth != null; }
    function role() { return signedIn() ? request.auth.token.role : ''; }
    function hasRole(roles) { return signedIn() && (role() in roles); }

${models}

    // config docs — readable by any signed-in member, writable by admins; history is append-only.
    match /config/{doc} {
      allow read: if signedIn();
      allow write: if hasRole(${list(admins)});
      match /history/{version} {
        allow read, create: if hasRole(${list(admins)});
        allow update, delete: if false;
      }
    }
  }
}
`;
}
