// src/materialize.mjs — turn a validated Spec into a DEPLOYABLE ARTIFACT BUNDLE (pure). The live
// inflection's safe half: planSpec (the gate) → applyPlan through a RECORDING executor that maps each
// op to a { path, content } file descriptor. No I/O here (the engine stays pure) — bin/materialize.mjs
// is the thin wrapper that actually writes the files, and later a Firebase-bound executor pushes the
// same ops to Firestore/Hosting instead of disk. Same plan, different executor: the seam doing its job.
//   materialize(spec) → { ok, errors, files: [{ path, content }] }
import { planSpec, applyPlan } from './plan.mjs';
import { buildRuntimeModel, renderRuntimeHTML } from './intake/runtime.mjs';

const json = v => JSON.stringify(v, null, 2);

export function materialize(spec) {
  const { ok, errors, plan, spec: cleaned } = planSpec(spec);
  if (!ok) return { ok: false, errors, files: [] };

  const files = [];
  const put = (path, content) => files.push({ path, content });

  // The filesystem executor: one op → one artifact. Mirrors what the Firebase executor will write to
  // config docs / rules / hosting, so a materialized bundle is exactly what a deploy would push.
  const exec = {
    writeConfig: op => put(`config/${String(op.doc).replace(/:/g, '/')}.json`, json(op.value)),
    registerPages: op => put('config/pages.json', json(op.pages)),
    genRulesFile: op => put(op.path || 'firestore.rules', String(op.rules)),
    snapshotSpec: () => put('config/appSpec.json', json(cleaned))   // the full cleaned spec = source of truth
  };
  applyPlan(plan, exec);

  // the RUNTIME SHELL — a self-contained, themed, navigable app. `firebase deploy --only hosting`
  // serves this index.html and you have a visitable app. (Live per-member data layers on later.)
  put('index.html', renderRuntimeHTML(buildRuntimeModel(cleaned, { demo: true })));

  // Firebase deploy config — hosting serves ONLY the app (index.html); the config/*.json + rules are
  // for Firestore seeding, not the web. So `firebase deploy` from this dir just works.
  put('firebase.json', json({
    hosting: { public: '.', ignore: ['firebase.json', '**/.*', 'config/**', 'firestore.rules', 'README.txt'] },
    firestore: { rules: 'firestore.rules' }
  }));

  // a small human-facing manifest so a bundle is self-describing
  put('README.txt', [
    `App: ${(cleaned.app && cleaned.app.name) || (cleaned.app && cleaned.app.id) || 'app'}`,
    `Modules: ${(cleaned.modules || []).map(m => m.type).join(', ') || '(none)'}`,
    `Data models: ${(cleaned.dataModels || []).map(m => m.id).join(', ') || '(none)'}`,
    `Pages: ${(cleaned.pages || []).map(p => p.id).join(', ') || '(none)'}`,
    '',
    'Generated by Appgnostic. Deploy the config/ docs + firestore.rules to your Firebase project',
    '(or point the Firebase executor at this bundle). Nothing here is executable.'
  ].join('\n'));

  return { ok: true, errors: [], files };
}
